// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: os-services.proto

package services

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message containing the folder name/path
type FolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderName    string                 `protobuf:"bytes,1,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderRequest) Reset() {
	*x = FolderRequest{}
	mi := &file_os_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderRequest) ProtoMessage() {}

func (x *FolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_os_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderRequest.ProtoReflect.Descriptor instead.
func (*FolderRequest) Descriptor() ([]byte, []int) {
	return file_os_services_proto_rawDescGZIP(), []int{0}
}

func (x *FolderRequest) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

// Response message containing the directory structure as a string
type FolderStructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Structure     string                 `protobuf:"bytes,1,opt,name=structure,proto3" json:"structure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderStructure) Reset() {
	*x = FolderStructure{}
	mi := &file_os_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderStructure) ProtoMessage() {}

func (x *FolderStructure) ProtoReflect() protoreflect.Message {
	mi := &file_os_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderStructure.ProtoReflect.Descriptor instead.
func (*FolderStructure) Descriptor() ([]byte, []int) {
	return file_os_services_proto_rawDescGZIP(), []int{1}
}

func (x *FolderStructure) GetStructure() string {
	if x != nil {
		return x.Structure
	}
	return ""
}

var File_os_services_proto protoreflect.FileDescriptor

const file_os_services_proto_rawDesc = "" +
	"\n" +
	"\x11os-services.proto\"0\n" +
	"\rFolderRequest\x12\x1f\n" +
	"\vfolder_name\x18\x01 \x01(\tR\n" +
	"folderName\"/\n" +
	"\x0fFolderStructure\x12\x1c\n" +
	"\tstructure\x18\x01 \x01(\tR\tstructure2E\n" +
	"\vFileService\x126\n" +
	"\x12GetFolderStructure\x12\x0e.FolderRequest\x1a\x10.FolderStructureB\x11Z\x0fpkg/os/servicesb\x06proto3"

var (
	file_os_services_proto_rawDescOnce sync.Once
	file_os_services_proto_rawDescData []byte
)

func file_os_services_proto_rawDescGZIP() []byte {
	file_os_services_proto_rawDescOnce.Do(func() {
		file_os_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_os_services_proto_rawDesc), len(file_os_services_proto_rawDesc)))
	})
	return file_os_services_proto_rawDescData
}

var file_os_services_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_os_services_proto_goTypes = []any{
	(*FolderRequest)(nil),   // 0: FolderRequest
	(*FolderStructure)(nil), // 1: FolderStructure
}
var file_os_services_proto_depIdxs = []int32{
	0, // 0: FileService.GetFolderStructure:input_type -> FolderRequest
	1, // 1: FileService.GetFolderStructure:output_type -> FolderStructure
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_os_services_proto_init() }
func file_os_services_proto_init() {
	if File_os_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_os_services_proto_rawDesc), len(file_os_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_os_services_proto_goTypes,
		DependencyIndexes: file_os_services_proto_depIdxs,
		MessageInfos:      file_os_services_proto_msgTypes,
	}.Build()
	File_os_services_proto = out.File
	file_os_services_proto_goTypes = nil
	file_os_services_proto_depIdxs = nil
}
